version: "3.8"

services:
  dashboards-desligamentos:
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      - "8096:8501"
    expose:
      - "8501"
